// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package inject

import (
	"github.com/Saser/strecku/internal/config"
	"github.com/Saser/strecku/internal/provide"
	"go.uber.org/zap"
)

// Injectors from zap.go:

func ZapDevelopmentLoggerFromConfig(config2 *config.Config) (*zap.Logger, func(), error) {
	atomicLevel := provide.ConfigLoggerLevel(config2)
	logger, err := provide.ZapDevelopmentLogger(atomicLevel)
	if err != nil {
		return nil, nil, err
	}
	return logger, func() {
	}, nil
}
