version: "3.7"

services:
  postgres:
    image: postgres:11.5
    environment:
      - POSTGRES_USER=integrationtest
      - POSTGRES_PASSWORD=integrationtest
      - POSTGRES_DB=integrationtest
    networks:
      - integrationtest
  integrationtest:
    build:
      context: ../../
      dockerfile: build/package/Dockerfile
    command: go test -race -cover -count=1 -tags=integrationtest ./...
    depends_on:
      - postgres
    networks:
      - integrationtest

networks:
  integrationtest:
